
checkpoint_path: "model.ckpt"
batch_size: 128
device: cpu
train_audio_path: "data/birdclef2025/train_audio" 
test_soundscape_path: "data/birdclef2025/train_soundscapes"


quantization:

  quantization_type: onnx  # none | dynamic | static | onnx
  per_channel: True
  calibration_data_path: "data/birdclef2025/train_soundscapes"
  n_calibration_samples: 200
  onnx_dir: .


temporal_smoothing:

  temporal_smoothing_type: neighbor_average # none | moving_average | triangular | savitzky | median | exponential | neighbor_average
  
  temporal_smoothing_params:

    neighbor_average:
      middle_chunks_weights: {
        prev: 0.1,
        curr: 0.8,
        next: 0.1
      }
      edge_chunk_weights: {
        main: 0.8,
        neighbor: 0.2
      }

    exponential:
      alpha: 0.3

    median:
      kernel_size: 3
    
    triangular:
      window_size: 3
    
    moving_average:
      window_size: 3

    savitzky:
      window_size: 3
      polyorder: 2

      

