checkpoint_path: "model.ckpt"
#"logdirs/checkpoints/efficientnet_b0_soft_ce_softmax/last.ckpt"
batch_size: 128

# inference paths
# local
train_audio_path: "data/birdclef2025/train_audio" 
test_soundscape_path: "data/birdclef2025/train_soundscapes"
calibration_dir: "data/birdclef2025/train_soundscapes"
# kaggle
# train_audio_path: "/kaggle/input/birdclef-2025/train_audio/"
# test_soundscape_path: "/kaggle/input/birdclef-2025/test_soundscapes/"

quantization:

  quantization_type: onnx  # none | dynamic | static | onnx
  per_channel: True
  calibration_data_path: "data/birdclef2025/train_soundscapes"
  n_calibration_samples: 200

temp_smoothing:
  use_temp_smoothing: True
  middle_chunks_weights: {
    prev: 0.2,
    curr: 0.6,
    next: 0.2
  }
  edge_chunk_weights: {
    main: 0.8,
    neighbor: 0.2
  }

