# Model architecture
backbone: tf_efficientnet_b0.in1k
pretrained: true

# Model parameters
device: cpu
n_classes: 206
classifier_dropout: 0.5
top_db: 80

# Spectrogram parameters
spec_params:
  sample_rate: ${data.dataset_args.sample_rate}
  n_mels: 128
  f_min: 20
  n_fft: 1024
  hop_length: 512
  normalized: true

normalize_config:
  normalize_standart: true
  normalize_minmax: true