
trainer:
  precision_mode: 16-mixed  # or 32-true
  train_strategy: auto
  n_epochs: 10
  log_every_n_steps: 4
  # val_check_interval: 4 # by epochs if commented out 

forward:
  loss_function: ce # bce # ce
  use_class_weights: True
  class_weights_temperature: 0.5

  output_key: logits # logits # softmax_predictions # sigmoid_predictions
  input_key: targets

  batch_key: specs

# soft_labels + softmax + CE 
# hard_labels + sigmoid + BCE

metrics:
  output_key: sigmoid_predictions # softmax_predictions # sigmoid_predictions
  input_key: targets_1d  
  

  names:
    - rocauc
  params:
    average: macro
    # task: multilabel
    # num_labels: ${model.n_classes}
    task: multiclass
    num_classes: ${model.n_classes}



optimizer:
  name: AdamW
  params:
    lr: 5e-4
    weight_decay: 1e-5


scheduler:
  name: CosineAnnealingLR
  params:
    eta_min: 1e-6
  config:
    interval: step
      


