# Training parameters

# trainer
trainer:
  precision_mode: 16-mixed  # or 32-true
  train_strategy: auto
  n_epochs: 1
  log_every_n_steps: 20
  val_check_interval: 200

# Optimizer
optimizer:
  name: AdamW
  params:
    lr: 5e-4
    weight_decay: 1e-5

# Scheduler
scheduler:
  name: CosineAnnealingLR
  params:
    # T_max: ${training.trainer.n_epochs} * (total_samples / batch_size) # set dynamically in train.py 
    eta_min: 1e-6
  config:
    interval: step
      

# Loss function
criterion: CrossEntropyLoss

# Metrics
metrics:
  names:
    # - accuracy
    # - recall
    # - precision
    # - f1
    - rocauc
  params:
    average: macro
    task: multilabel
    num_labels: ${model.n_classes}

    # task: multiclass
    # num_classes: ${model.n_classes}


