hydra:
  run:
    # for augmentations runs
    dir: "../../hydra_logs/augmentations"
  output_subdir: ${now:%Y-%m-%d_%H-%M-%S}

defaults:
  - _self_
  - data: data
  - augmentation: augmentation
  - model: model
  - training: training
  - inference: inference

# Global settings
seed: 42
debug: false
output_dir: .
experiment_name: logdirs/efficientnet_b0__weights_power-0.5

device: "cpu"   # or "cpu" if you prefer

# Logging (if used later)
wandb:
  project: audio-classification
  entity: 'BashHav'
  name: ${experiment_name}
  tags: []
  
callbacks:
  n_checkpoints_to_save: 3
  metric_mode: max
  main_metric: valid/MulticlassAUROC
