hydra:
  run:
    dir: "../../hydra_logs"
  output_subdir: ${now:%Y-%m-%d_%H-%M-%S}

defaults:
  - _self_
  - data: data
  - augmentation: augmentation
  - model: model
  - training: training
  - inference: inference

seed: 42
debug: false
output_dir: .
experiment_name: efficientnet_b0_soft_ce_softmax

device: "cpu"   


wandb:
  project: audio-classification
  entity: 'BashHav'
  name: ${experiment_name}
  log_model: all
  
callbacks:
  # checkpoint_dir: logdirs/${experiment_name}/checkpoints

  n_checkpoints_to_save: 3
  metric_mode: max
  main_metric: valid/MulticlassAUROC

  save_last: True
  auto_insert_metric_name: True
  save_weights_only: True
  save_on_train_epoch_end: True
