# Audio augmentations
audio:
  # just comment out to run without audio augmentatinos
  # audio_transforms:
  #   - name: "gaussian_noise"
  #     params:
  #       min_amplitude: 0.001
  #       max_amplitude: 0.015
  #       p: 0.5

  #   - name: "time_stretch"
  #     params:
  #       min_rate: 0.8
  #       max_rate: 1.2
  #       p: 0.5

  #   - name: "pitch_shift"
  #     params:
  #       min_semitones: -4
  #       max_semitones: 4
  #       p: 0.5
  

# Spectrogram augmentations
# just comment out to run without spec augmentatinos
spectrogram: 
  freq_mask:
    mask_max_length: 20
    mask_max_masks: 5
    p: 1
    inplace: true
  time_mask:
    mask_max_length: 30
    mask_max_masks: 5
    p: 1
    inplace: true
